<?php

namespace App\Rules\Api\Tenant;

use Illuminate\Validation\Rule;

class VisitaTenantRule
{
    public function rules($id, $connection = null)
    {
        return [
            
            "idFilial"=>[
                'required',
                'int',
                "exists:{$connection}.filial,id"
            ],
            "idMotivo"=>[
                'nullable',
                'int',
                "exists:{$connection}.motivo,id"
            ],
            "idVendedor"=>[
                'required',
                'int',
                "exists:{$connection}.vendedor,id"
            ],
            "idCliente"=>[
                'required',
                'int',
                "exists:{$connection}.cliente,id"
            ],
            "idPedidoDispositivo"=>[
                'required',
                'int'
            ],
            "status"=>[
                'required',
                'int',
                Rule::in(0,1,2,3,5,6,7)
                
            ],
            "sincErp"=>[
                'required',
                'int'
            ],
            "dtMarcada"=>[
                'nullable',
                'date'
            ],
            "horaMarcada"=>[
                'nullable',
                'date_format:H:i'
            ],
            'observacao'=>[
                'nullable',
                'string',
                'max:255'
            ],
            'ordem'=>[
                'nullable',
                'int'
            ],
            'latitude'=>[
                'nullable',
                'string'
            ],
            'longitude'=>[
                'nullable',
                'string'
            ],
            'precisao'=>[
                'nullable',
                'string'
            ],
            'provedor'=>[
                'nullable',
                'string'
            ],
            'latInicio'=>[
                'nullable',
                'string'
            ],
            'lngInicio'=>[
                'nullable',
                'string'
            ],
            'latFinal'=>[
                'nullable',
                'string'
            ],
            'lngFinal'=>[
                'nullable',
                'string'
            ],
            'precisaoInicio'=>[
                'nullable',
                'string'
            ],
            'precisaoFinal'=>[
                'nullable',
                'string'
            ],
            'horaIni'=>[
                'nullable',
                'date_format:H:i',
                'before_or_equal:horaFinal'
            ],
            'horaFim'=>[
                'nullable',
                'date_format:H:i',
                'after_or_equal:horaInicio'
            ],
            'dtCadastro'=>[
                'nullable',
                'date'
            ],
            'enderecoExtensoGoogle'=>[
                'nullable',
                'string',
                'max:255'
            ],
            'agendadoErp'=>[
                'required',
                'int'
            ]

        ];
    }
}