version: '3'

services:

  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=central_afv
      - MYSQL_USER=painel_temporario
      - MYSQL_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
      - ./database/dump:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mariadb -h localhost -u root -p'123456' -e 'USE central_afv; SELECT COUNT(*) FROM versao_app';"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 50s
