FROM php:7.4-fpm

RUN apt-get update && \
    apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev unzip && \
    docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install -j$(nproc) gd mysqli pdo pdo_mysql pcntl

WORKDIR /var/www/html

COPY ./src .

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

EXPOSE 9000 6000

CMD ["php-fpm"]