version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=central_afv
      - MYSQL_USER=painel_temporario
      - MYSQL_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
      - ./central_afv.sql:/tmp/central_afv.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3