name: ManagerV2-Backend-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'    
    - uses: actions/checkout@v3.1.0

    - name: Build do banco de dados
      run: docker compose build

    - name: Iniciando container do banco de dados
      run: docker compose up -d

    - name: Aguardando o banco iniciar
      run: sleep 30
    
    - name: Verificando se o container esta em execução
      run: docker container exec managerv2-backend-mariadb-1 mariadb -h 127.0.0.1 -u root -p'123456' -e 'USE central_afv; SELECT COUNT(*) FROM versao_app';

    - name: Install Dependencies
      run: composer install
    
    - name: Testes unitários
      run: php artisan test

    - name: Send custom JSON data to Slack workflow
      if: failure()
      id: slack
      uses: slackapi/slack-github-action@v1.25.0
      with:
        payload: |
          {
            "text": "Resultado Github Action: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Resultado Github Action: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
         

  Dockerhub-Image:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Autenticação no Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Construção da imagem Docker do backend
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            matheussig2000/managerv2-backend:V${{github.run_number}}
            matheussig2000/managerv2-backend:latest